[global]
   workgroup = WORKGROUP
   server string = SOC Windows Server 2022
   netbios name = SOC-WINDOWS
   security = user
   map to guest = Bad User
   dns proxy = no
   log file = /var/log/samba/log.%m
   max log size = 1000
   log level = 1 auth:3
   passdb backend = tdbsam

[LabShare]
   comment = Synthetic training document. No production data.
   path = /storage/LabShare
   read only = yes
   guest ok = no
   valid users = student
   browseable = yes
