[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
priority=10
autorestart=true

[program:smbd]
command=/usr/sbin/smbd -F --no-process-group
priority=20
autorestart=true

[program:sshd]
command=/usr/sbin/sshd -D
priority=20
autorestart=true

[program:vsftpd]
command=/usr/sbin/vsftpd /etc/vsftpd.conf
priority=20
autorestart=true

[program:telemetry]
command=/usr/bin/python3 /opt/telemetry_server.py
priority=30
autorestart=true

[program:filebeat]
command=/usr/share/filebeat/bin/filebeat -e -c /etc/filebeat/filebeat.yml --strict.perms=false
priority=40
autorestart=true
