listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=NO
local_enable=YES
write_enable=NO
pam_service_name=vsftpd
xferlog_enable=YES
log_ftp_protocol=YES
vsftpd_log_file=/var/log/vsftpd.log
seccomp_sandbox=NO
pasv_min_port=50000
pasv_max_port=50005
